package CifradoresClasicos;

import CifradoresClasicos.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis Cuevas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TituloMenu = new javax.swing.JLabel();
        vigenere = new javax.swing.JRadioButton();
        validarKey = new javax.swing.JRadioButton();
        affine = new javax.swing.JRadioButton();
        Inicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TituloMenu.setText("Cifradores clásicos");

        buttonGroup1.add(vigenere);
        vigenere.setText("Cifrado de Vigenère");
        vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenereActionPerformed(evt);
            }
        });

        buttonGroup1.add(validarKey);
        validarKey.setText("Validar key K(a,b) con n");

        buttonGroup1.add(affine);
        affine.setText("Cifrador Afín");
        affine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affineActionPerformed(evt);
            }
        });

        Inicar.setText("Iniciar");
        Inicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona una operación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(TituloMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(validarKey, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vigenere, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(affine, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Inicar)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TituloMenu)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vigenere)
                .addGap(18, 18, 18)
                .addComponent(validarKey)
                .addGap(18, 18, 18)
                .addComponent(affine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inicar)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigenereActionPerformed

    private void affineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affineActionPerformed

    private void InicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicarActionPerformed
        if (vigenere.isSelected()){
            GUI_Vigenere a = new GUI_Vigenere();
            a.setVisible(true);
            this.setVisible(false);
        }
        else if (validarKey.isSelected()){
            GUI_ValidarK a= new GUI_ValidarK();
            a.setVisible(true);
            this.setVisible(false);
        }
        else if (affine.isSelected()){
            GUI_Afin a= new GUI_Afin();
            a.setVisible(true);
            this.setVisible(false);
        }
            
    }//GEN-LAST:event_InicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inicar;
    private javax.swing.JLabel TituloMenu;
    private javax.swing.JRadioButton affine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton validarKey;
    private javax.swing.JRadioButton vigenere;
    // End of variables declaration//GEN-END:variables
}
